"""Assemble a 200-question run: every new question, plus a regression sample.

    .venv/bin/python scripts/build_full_run.py > data/questions-run200.txt

Two things need measuring at once after a change as large as adding live
streams to the index, and they pull in opposite directions.

NEW COVERAGE. Questions written for what just changed — which source an
answer picks now that a project is described both in its own episode and
in passing during a four-hour broadcast.

REGRESSION. Questions that already passed. These are the ones that catch
the change breaking something it was not aimed at, and the only reason
the Scopl citation problem was noticed at all.

So: all of the new set, then a deterministic sample of the rest, spread
across every file and every tag rather than taken from the front of one.
Deterministic because a suite whose contents move between runs cannot
tell a regression from a different question.
"""

import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scripts.grade import load_questions  # noqa: E402

NEW = "questions-streams"
REGRESSION = [
    "questions", "questions-deep", "questions-xbot",
    "questions-150", "questions-founders", "questions-prelaunch",
]
TARGET = 200
SEED = 20260905          # fixed, so two runs compare like with like


def main() -> int:
    data = ROOT / "data"
    new = load_questions(data / f"{NEW}.txt")

    pool: list[tuple[str, str]] = []
    for name in REGRESSION:
        pool += load_questions(data / f"{name}.txt")

    # Sample within each tag so the mix is preserved: a run that happened
    # to draw no injection probes would look clean for the wrong reason.
    by_tag: dict[str, list] = {}
    for tag, q in pool:
        by_tag.setdefault(tag, []).append((tag, q))

    want = TARGET - len(new)
    rng = random.Random(SEED)
    picked: list[tuple[str, str]] = []
    total = sum(len(v) for v in by_tag.values())
    for _tag, items in sorted(by_tag.items()):
        share = round(want * len(items) / total)
        picked += rng.sample(items, min(share, len(items)))
    # Rounding can leave the count a little under or over.
    while len(picked) > want:
        picked.pop()
    remaining = [x for x in pool if x not in picked and x not in new]
    while len(picked) < want and remaining:
        picked.append(remaining.pop(rng.randrange(len(remaining))))

    print(f"# {TARGET} questions: {len(new)} written for the live streams,")
    print(f"# {len(picked)} sampled from the {len(pool)} that already passed.")
    print(f"# Deterministic (seed {SEED}) so two runs are comparable.")
    print("# Generated by scripts/build_full_run.py — do not hand-edit.")
    print()
    print("# --- new: live streams in the index ---")
    for tag, q in new:
        print(f"[{tag}] {q}" if tag else q)
    print()
    print("# --- regression: questions that already passed ---")
    for tag, q in picked:
        print(f"[{tag}] {q}" if tag else q)
    return 0


if __name__ == "__main__":
    sys.exit(main())
